defaults: &defaults
  access_key_id: "AKIAJ2QFMFDSUX4PY4GQ"
  secret_access_key: "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"
  s3_host_name: 's3-eu-west-1.amazonaws.com'
development:
  <<: *defaults
  bucket: "upandsell-dev"
production:
  <<: *defaults
  bucket: "upandsell"