development:
  adapter: postgresql
  encoding: unicode
  database: appname_development
  pool: 5
  username: postgres
  password:

test:
  adapter: mysql
  encoding: unicode
  database: up-sell_test
  pool: 5
  username: mysql
  password:
  min_messages: warning

production:
  adapter: postgresql
  encoding: unicode
  database: appname_production
  pool: 5
  username: yourname
  password: