test: &default

  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: cicio_api1.galluzzo.me
  password: '1380265896'
  signature: ACXOynAE4-4hmGxsXPS1TQ2mkkDIAkkcSXkACzxwx9jAOOKTEmzGvEFw
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: mail-facilitator@roccogalluzzo.com

  # # IP Address
  #ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  #mode: live
